version: '3.8'

services:
  postgres:
    image: postgres:17.4
    container_name: b_maps-postgres
    ports:
      - "5422:5432"
    environment:
      POSTGRES_DB: b_maps
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
